#### 1. What is a Python library? Why do we use Python libraries?

#### 2. What is the difference between Numpy array and List ?

#### 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [53]:
import numpy as np

arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])


print('Array: ', arr)

print(f'\nShape = {arr.shape}, Size = {arr.size}, Dimension = {arr.ndim}')

Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape = (3, 4), Size = 12, Dimension = 2


#### 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [54]:
arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print('First row of Array is : ')
arr[0]

First row of Array is : 


array([1, 2, 3, 4])

#### 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [55]:
arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print('The element at the third row and fourth column is : ', arr[2,3])


The element at the third row and fourth column is :  12


#### 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [56]:
arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

# Considering indexing starts from 0 for both rows and columns in numpy, odd-indexes are 1 and 3
#so odd indexed rows = 1
#and odd indexed columns = 1 and 3

print('Odd-indexed elements : ')
arr[1::2,1::2]

Odd-indexed elements : 


array([[6, 8]])

#### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [57]:
print('Random 3x3 matrix with values between 0 and 1 is: ')
np.random.rand(3,3)

Random 3x3 matrix with values between 0 and 1 is: 


array([[0.26273625, 0.26424041, 0.95874724],
       [0.28521882, 0.19621238, 0.19889369],
       [0.40173001, 0.33569244, 0.22032649]])

#### 8. Describe the difference between np.random.rand and np.random.randn?

#### 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [58]:
arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print('Initial array : ', arr)
print(f'Initial dimension : {arr.ndim}, Initial shape: {arr.shape}')


print(f'\n1) Expanding dimension on axis=0 :')
arr_0 = np.expand_dims(arr, axis=0)
print('Final array : ', arr_0)
print(f'Final dimension : {arr_0.ndim}, Final shape: {arr_0.shape}')


print(f'\n2) Expanding dimension on axis=1 :')
arr_1 = np.expand_dims(arr, axis=1)
print('Final array : ', arr_1)
print(f'Final dimension : {arr_1.ndim}, Final shape: {arr_1.shape}')

Initial array :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Initial dimension : 2, Initial shape: (3, 4)

1) Expanding dimension on axis=0 :
Final array :  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Final dimension : 3, Final shape: (1, 3, 4)

2) Expanding dimension on axis=1 :
Final array :  [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
Final dimension : 3, Final shape: (3, 1, 4)


#### 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [59]:
arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print('Transpose of array: ')
np.transpose(arr)

Transpose of array: 


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### 11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operations using Python:
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrices
4. Subtract matrix B from A
5. Divide Matrix B by A

In [60]:
matrixA = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

matrixB = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

#1. Index wise multiplication
print('1). Index wise multiplication : ', matrixA * matrixB)

#2. Matrix multiplication
print('\n2). Matrix multiplication : ')
print('Matrix multiplication is denoted by matrixA @ matrixB.')
print(f'Shape of matrixA: {matrixA.shape}\tShape of matrixB: {matrixB.shape}')
print('It will throw error since matrixA column count is not equal to matrixB row count.')

#3. Add both the matrices
print('\n3). Addition of matrices : ', matrixA + matrixB)

#4. Subtract matrix B from A
print('\n4). Subtract B from A : ', matrixA - matrixB)

#5. Divide Matrix B by A
print('\n5). Divide B by A : ', matrixB / matrixA)

1). Index wise multiplication :  [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2). Matrix multiplication : 
Matrix multiplication is denoted by matrixA @ matrixB.
Shape of matrixA: (3, 4)	Shape of matrixB: (3, 4)
It will throw error since matrixA column count is not equal to matrixB row count.

3). Addition of matrices :  [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4). Subtract B from A :  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5). Divide B by A :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 12. Which function in Numpy can be used to swap the byte order of an array?

In [66]:
# byteswap() is used to swap the byte order of an array. For example:
a = np.array([1, 2, 3, 4])

a.byteswap()


array([16777216, 33554432, 50331648, 67108864])

#### 13. What is the significance of the np.linalg.inv function?

In [103]:
#np.linalg.inv is a numpy function that computes the multiplicative inverse of a matrix.
#Given a square matrix a, return the matrix a_inv satisfying dot(a, a_inv) = dot(a_inv, a) = eye(a.shape[0]).

#example
a = np.matrix([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)
print('Inverse of matrix a is : \n', a_inv)

Inverse of matrix a is : 
 [[-2.   1. ]
 [ 1.5 -0.5]]


#### 14. What does the np.reshape function do, and how is it used?

In [121]:
# np.reshape function gives a new shape to an array without changing its data. 
# The new shape should be compatible with the original shape. The size always remains same.

arr = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print('Initial array : \n', arr, '\t\tShape:', arr.shape, '\tSize:', arr.size)

arr1 = np.reshape(arr, (4,3))
print('\nReshaped array 1: \n', arr1, '\t\t\tShape:', arr1.shape, '\tSize:', arr1.size)

arr2 = np.reshape(arr, (2,6))
print('\nReshaped array 2: \n', arr2, '\t\tShape:', arr2.shape, '\tSize:', arr2.size)

Initial array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 		Shape: (3, 4) 	Size: 12

Reshaped array 1: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 			Shape: (4, 3) 	Size: 12

Reshaped array 2: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 		Shape: (2, 6) 	Size: 12


#### 15. What is broadcasting in Numpy?

In [131]:
'''
The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during 
arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ 
across the larger one, ensuring that they have compatible shapes for these operations.
Broadcasting allows NumPy to handle arrays with different shapes during operations, making 
vectorized computations more efficient and eliminating the need for explicit loops
'''
# Example:
a = np.array([[5, 7, 3], [2, 1, 0], [4, 6, 1]])    #3x3 array
b = np.array([1, 3, 1])                            #1x3 array

print('a: ', a)
print('\nb: ', b)
# If we add the smaller array 'b' to the larger array 'a', then it is referred as Broadcasting.
# The smaller array 'b' is conceptually stretched to become an array with the same shape as 'a', allowing 
# element-wise addition.
c = a + b 
print('\nResult when b is broadcasted : \n', c) 

a:  [[5 7 3]
 [2 1 0]
 [4 6 1]]

b:  [1 3 1]

Result when b is broadcasted : 
 [[ 6 10  4]
 [ 3  4  1]
 [ 5  9  2]]
